spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/snsCard?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: DingYu,!199000521
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: bootTest
server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.example.bootTest.pojo
  mapper-locations: classpath:mapper/*.xml
decorator:
  datasource:
    p6spy:
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      # 自定义日志类